# coding: utf-8

"""
    Coinbase Platform API

    This is the OpenAPI 3.0 specification for the Coinbase Platform APIs, used in conjunction with the Coinbase Platform SDKs.

    The version of the OpenAPI document: 0.0.1-alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SmartContractType(str, Enum):
    """
    The type of the smart contract.
    """

    """
    allowed enum values
    """
    ERC20 = 'erc20'
    ERC721 = 'erc721'
    ERC1155 = 'erc1155'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SmartContractType from a JSON string"""
        return cls(json.loads(json_str))


