# coding: utf-8

"""
    Coinbase Platform API

    This is the OpenAPI 3.0 specification for the Coinbase Platform APIs, used in conjunction with the Coinbase Platform SDKs.

    The version of the OpenAPI document: 0.0.1-alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ValidatorStatus(str, Enum):
    """
    The status of the validator.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    PROVISIONING = 'provisioning'
    PROVISIONED = 'provisioned'
    DEPOSITED = 'deposited'
    PENDING_ACTIVATION = 'pending_activation'
    ACTIVE = 'active'
    EXITING = 'exiting'
    EXITED = 'exited'
    WITHDRAWAL_AVAILABLE = 'withdrawal_available'
    WITHDRAWAL_COMPLETE = 'withdrawal_complete'
    ACTIVE_SLASHED = 'active_slashed'
    EXITED_SLASHED = 'exited_slashed'
    REAPED = 'reaped'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ValidatorStatus from a JSON string"""
        return cls(json.loads(json_str))


